version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=process.env.REACT_APP_API_URL
    depends_on:
      - backend

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - MONGODB_URI=process.env.DATABASE_URL
